const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const dataujiScehma = new Schema({
    no_plat : String ,
    nouji: String,
    nomesin: String,
    statuspenerbitan: Number,
    fotodepansmall: String,
    fotobelakangsmall: String,
    fotokanansmall: String,
    fotokirismall: String,
    idpetugasuji: Number,
    idkepaladinas: Number,
    iddirektur: Number,
    kodewilayah: String,
    kodewilayahasal: String,
    huv_nomordankondisirangka: String,
    huv_nomordantipemotorpenggerak: String,
    huv_kondisitangkicorongdanpipabahanbakar: String,
    huv_kondisiconverterkit: String,
    huv_kondisidanposisipipapembuangan: String,
    huv_ukurandankondisiban: String,
    huv_kondisisistemsuspensi: String,
    huv_kondisisistemremutama: String,
    huv_kondisipenutuplampudanalatpantulcahaya: String,
    huv_kondisipanelinstrumentdashboard: String,
    huv_kondisikacaspion: String,
    huv_kondisispakbor: String,
    huv_bentukbumper: String,
    huv_keberadaandankondisiperlengkapan: String,
    huv_rancanganteknis: String,
    huv_keberadaandankondisifasilitastanggapdaruratuntukmobilbus: String,
    huv_kondisibadankacaengseltempatdudukmbarangbakmuatantertutup: String,
    hum_kondisipenerusdaya: String,
    hum_sudutbebaskemudi: String,
    hum_kondisiremparkir: String,
    hum_fungsilampudanalatpantulcahaya: String,
    hum_fungsipenghapuskaca: String,
    hum_tingkatkegelapankaca: String,
    hum_fungsiklakson: String,
    hum_kondisidanfungsisabukkeselamatan: String,
    hum_ukurankendaraan: String,
    hum_ukurantempatdudukdanbagiandalamkendaraanuntukmobilbus: String,
    alatuji_emisiasapbahanbakarsolar: String,
    alatuji_emisicobahanbakarbensin: String,
    alatuji_emisihcbahanbakarbensin: String,
    alatuji_remutamatotalgayapengereman: String,
    alatuji_remutamaselisihgayapengeremanrodakirikanan1: String,
    alatuji_remutamaselisihgayapengeremanrodakirikanan2: String,
    alatuji_remutamaselisihgayapengeremanrodakirikanan3: String,
    alatuji_remutamaselisihgayapengeremanrodakirikanan4: String,
    alatuji_remparkirtangan: String,
    alatuji_remparkirkaki: String,
    alatuji_kincuprodadepan: String,
    alatuji_tingkatkebisingan: String,
    alatuji_lampuutamakekuatanpancarlampukanan: String,
    alatuji_lampuutamakekuatanpancarlampukiri: String,
    alatuji_lampuutamapenyimpanganlampukanan: String,
    alatuji_lampuutamapenyimpanganlampukiri: String,
    alatuji_penunjukkecepatan: String,
    alatuji_kedalamanalurban: String,
    masaberlakuuji: String,
    tgluji: Date,
    statuslulusuji: String,
    created_at: {
        type: Date,
        default: new Date().toISOString()
    }
});

module.exports = mongoose.model("data_pengujian", dataujiScehma);