const mongoose = require("mongoose");
const Schema = mongoose.Schema;
const kendaraan = new Schema({
  deleted: {
    type: Boolean,
    default: false,
  },
  jeniskaroseri:String,
  bahankaroseri: String,
  banyaktempatduduk: String,
  banyaktempatberdiri:String,
  warnatnbk: String,
  nouji: String,
  nama: String,
  alamat: String,
  noidentitaspemilik: String,
  nosertifikatreg: String,
  tglsertifikatreg: String,
  noregistrasikendaraan: String,
  norangka: String,
  nomesin: String,
  merek: String,
  tipe: String,
  jenis: String,
  thpembuatan: String,
  bahanbakar: String,
  isisilinder: String,
  dayamotorpenggerak: String,
  jbb: String,
  jbkb: String,
  jbi: String,
  jbki: String,
  mst: String,
  beratkosong: String,
  konfigurasisumburoda: String,
  panjangkendaraan: String,
  lebarkendaraan: String,
  tinggikendaraan: String,
  panjangbakatautangki: String,
  lebarbakatautangki: String,
  tinggibakatautangki: String,
  julurdepan: String,
  julurbelakang: String,
  jaraksumbu1_2: String,
  jaraksumbu2_3: String,
  jaraksumbu3_4: String,
  dayaangkutorang: String,
  dayaangkutbarang: String,
  kelasjalanterendah: String,
  created_at: {
    type: Date,
    default: new Date().toISOString(),
  },
});

module.exports = mongoose.model("kendaraan", kendaraan);
