const mongoose = require("mongoose");
const Schema = mongoose.Schema;
const pengujian = new Schema({
  nouji: String,
  nomesin: String,
  statuspenerbitan: Number,
  ukuranban: String,
  fotodepansmall: String,
  fotobelakangsmall: String,
  fotokanansmall: String,
  fotokirismall: String,
  idpetugasuji: Number,
  idkepaladinas: Number,
  iddirektur: Number,
  kodewilayah: String,
  kodewilayahasal: String,
  huv_nomordankondisirangka: Number,
  huv_nomordantipemotorpenggerak: Number,
  huv_kondisitangkicorongdanpipabahanbakar: Number,
  huv_kondisiconverterkit: Number,
  huv_kondisidanposisipipapembuangan: Number,
  huv_ukurandankondisiban: Number,
  huv_kondisisistemsuspensi: Number,
  huv_kondisisistemremutama: Number,
  huv_kondisipenutuplampudanalatpantulcahaya: Number,
  huv_kondisipanelinstrumentdashboard: Number,
  huv_kondisikacaspion: Number,
  huv_kondisispakbor: Number,
  huv_bentukbumper: Number,
  huv_keberadaandankondisiperlengkapan: Number,
  huv_rancanganteknis: Number,
  huv_keberadaandankondisifasilitastanggapdaruratuntukmobilbus: String,
  huv_kondisibadankacaengseltempatdudukmbarangbakmuatantertutup: Number,
  hum_kondisipenerusdaya: Number,
  hum_sudutbebaskemudi: Number,
  hum_kondisiremparkir: Number,
  hum_fungsilampudanalatpantulcahaya: Number,
  hum_fungsipenghapuskaca: Number,
  hum_tingkatkegelapankaca: Number,
  hum_fungsiklakson: Number,
  hum_kondisidanfungsisabukkeselamatan: Number,
  hum_ukurankendaraan: Number,
  hum_ukurantempatdudukdanbagiandalamkendaraanuntukmobilbus: Number,
  alatuji_emisiasapbahanbakarsolar: String,
  alatuji_emisicobahanbakarbensin: String,
  alatuji_emisihcbahanbakarbensin: String,
  alatuji_remutamatotalgayapengereman: String,
  alatuji_remutamaselisihgayapengeremanrodakirikanan1: String,
  alatuji_remutamaselisihgayapengeremanrodakirikanan2: String,
  alatuji_remutamaselisihgayapengeremanrodakirikanan3: String,
  alatuji_remutamaselisihgayapengeremanrodakirikanan4: String,
  alatuji_remparkirtangan: String,
  alatuji_remparkirkaki: String,
  alatuji_kincuprodadepan: String,
  alatuji_tingkatkebisingan: String,
  alatuji_lampuutamakekuatanpancarlampukanan: String,
  alatuji_lampuutamakekuatanpancarlampukiri: String,
  alatuji_lampuutamapenyimpanganlampukanan: String,
  alatuji_lampuutamapenyimpanganlampukiri: String,
  alatuji_penunjukkecepatan: String,
  alatuji_kedalamanalurban: String,
  masaberlakuuji: String,
  tgluji: Date,
  statuslulusuji: String,
  created_at: {
    type: Date,
    default: new Date().toISOString(),
  },
});

module.exports = mongoose.model("pengujian", pengujian);
